name: yt_flutter_musicapi_example
description: "Demonstrates how to use the yt_flutter_musicapi plugin."
publish_to: 'none'

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher:
  yt_flutter_musicapi:
    path: ../
  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_icon.png

# ✅ This must be at the top level, NOT inside `flutter:`
flutter_icons:
  android: true
  image_path: assets/icons/app_icon.png
  adaptive_icon_foreground: assets/icons/app_icon.png
  adaptive_icon_background: "#FFFFFF"
